### ISSUE TITLE
Constructive Criticism for Glowing Potato

### ISSUE THREAD

**Issue by DimitriyL** [kristinlin/glowing-potato#1]
For the most part, any issues with your page are aesthetic in nature. While you have a title, I would have wished for you to also include axis labels (or, really, any labels at all). I really have no sense of which circle is supposed to represent which planet, or what the relative distances along the y-axis of the SVG are supposed to mean. 
Axis labels are actually something that I struggled with myself, but they are fairly easy to put in, so long as you style them around your SVG container with enough padding.
Additionally, while you included eight planets and corresponding number values, I would have liked a more clear indicator of which planet is which.
Other than that, it works well.
--Dimitriy and Sonal

**Comment by kristinlin** [comment]
Thanks for the input!
